### ISSUE TITLE
Focus on semantic segmentation

### ISSUE THREAD

**Issue by nickstheisen** [nickstheisen/hyperseg#5]
The projects focus is on hyperspectral semantic segmentation. Pixel classification and single image datasets are not really suitable for semantic segmentation. The parts that are concerned with this bloat the repository and make the structure more complex. They should therefore be removed.

### TODOs

- [x] Remove code for single image datasets
- [x] Remove code for pixel classification models
- [x] Simplify and refactor the repository structure
- [x] Make sure training is still working
